### PR TITLE
feat: add `q` query param for search

### PR DESCRIPTION
**Pull request by boredcity**
On the web state of the search input is stored in the URL instead of the widget state now. This allows restoring state from URL / sharing URLs.

### List of issues which are fixed by the PR
#453

### Screenshots
*If applicable, add screenshots to help explain the changes.*

### Checklist

- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on [Discord].

[CLA]: https://docs.google.com/forms/d/e/1FAIpQLScuRfjUzENsLsmQgqZlGLxMKbFi7zuXoPARyXytoyQrq7ntUw/viewform
[Discord]: https://discord.com/invite/zT4AMStAJA

### CODE REVIEW

**Comment by boredcity** [comment]
CLA link seems to be broken + I was never assigned to the issue, I will try to clean this up if the changes are useful and you're ok with me working on this PR. :)

**Review by YoussefRaafatNasry — CHANGES_REQUESTED** [review]
While the approach you took definitely works, but it's hard to test.
The way we currently handle the query parameters is through the [`AppRouteConfig`](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/lib/src/routing/app_route_config.dart) and [`WidgetbookState`](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/lib/src/state/widgetbook_state.dart). You can follow the `path` query parameter and see how it's used/implemented.

General comments:
1. Tests should be included to validate the new change.
1. Changing the search field should update the query parameters (similar to when you click a use-case, the query paramter `path` reflect the change).

**Comment by boredcity** [comment]
on a work trip this week, will work on it on the weekend 👍

**Comment by boredcity** [comment]
Just updated the logic. Currently `packages/widgetbook/test/src/navigation/widgets/navigation_panel_test.dart` is failing since the widget now uses `WidgetbookState.of(context)` and tests do not provide it in the component tree. Is there an example in the project of a similar problem resolved?

**Comment by YoussefRaafatNasry** [comment]
Hello @boredcity 👋 
You can use [`pumpWidgetWithState`](https://github.com/widgetbook/widgetbook/blob/5fd04ef6bc01c35a696c46c328116914ca923619/packages/widgetbook/test/helper/tester_extension.dart#L50-L64) and see how it's used.

**Comment by boredcity** [comment]
@YoussefRaafatNasry huge thanks, fixed the test with `pumpWidgetWithQueryParams`, all tests pass locally, waiting to confirm the same happens for CI 👍

**Comment by boredcity** [comment]
@YoussefRaafatNasry Hi, thank you! Did it 6 days ago but no replies so far :/

Screenshot 2023-11-30 at 17 54 19

**Pull request merged**
