### PR TITLE
feat: confirm before exit on mobile devices

### PR DESCRIPTION
**Pull request by IvanGael**
*Replace this paragraph with a description of what this PR is changing or adding, and why.*

### List of issues which are fixed by the PR
when we accidentally click on Hardware button in Android, whole application is closed.

### Screenshots
*If applicable, add screenshots to help explain the changes.*

### Checklist

- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on [Discord].

[CLA]: https://docs.google.com/forms/d/e/1FAIpQLScuRfjUzENsLsmQgqZlGLxMKbFi7zuXoPARyXytoyQrq7ntUw/viewform
[Discord]: https://discord.com/invite/zT4AMStAJA

### CODE REVIEW

**Comment by mjablecnik** [comment]
Hello, I added your version into my test project but exit dialog doesn't show me.

Screenshot 2024-06-23 at 7 24 43

**Comment by IvanGael** [comment]
@mjablecnik The change have been made on this file https://github.com/IvanGael/widgetbook/blob/main/packages/widgetbook/lib/src/layout/mobile_layout.dart

Just a question! In the widgetbook project folder, which folder should I run in order to test the changes?

**Comment by mjablecnik** [comment]
@IvanGael 

> In the widgetbook project folder, which folder should I run in order to test the changes?

You can run some [example](https://github.com/widgetbook/widgetbook/tree/main/examples) and test it there..

**Review by YoussefRaafatNasry — COMMENTED** [review]
Thanks for you contribution, @IvanGael!
I will wait for @mjablecnik to validate that the change works for them, as they are the one who raised the issuse.

In the mean time, please conside the following:
1. Checking out all unrelated changes, like `pubspec.lock` files and other files. These files showed up because you have used `flutter pub get` instead of `melos bootstrap` to get the dependecies in the monorepo, more information can be found [here](https://docs.widgetbook.io/contribution/get-started).
1. Add some tests.
1. Add an entry in [CHANGELOG](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/CHANGELOG.md) under new `## Unreleased` headline.

**Comment by IvanGael** [comment]
Hello @mjablecnik I tested a full example here https://github.com/widgetbook/widgetbook/tree/main/examples  but I don't see any change despite the fact that some changes have been made on this file https://github.com/IvanGael/widgetbook/blob/main/packages/widgetbook/lib/src/layout/mobile_layout.dart

**Comment by YoussefRaafatNasry** [comment]
Hello @IvanGael 👋 

Please make sure that your development environment is set up correctly.
It seems like you are using the hosted Widgetbook package and not the local one, which has the changes you made.

To do so set up everything correctly, use `melos` as mentioned [here](https://docs.widgetbook.io/contribution/get-started).

**Comment by IvanGael** [comment]
@YoussefRaafatNasry I set up melos and it seems everything is good. How to use the local widgetbook package instead of which is hosted ?

**Comment by YoussefRaafatNasry** [comment]
@IvanGael After installing melos, you need to:
1. Undo all the `pubspec.lock` files changes in this PR.
2. Run `melos bs` to install the dependancies and use the local Widgetbook version.

**Comment by mjablecnik** [comment]
@IvanGael Any progress?

**Comment by IvanGael** [comment]
@mjablecnik Not done yet. I need to take a look on this because i have tried what @YoussefRaafatNasry suggested to me but It seems there is

**Comment by yousinix** [comment]
I will be closing this PR for staying stale.
Please re-open a new one once it's ready to review.

**Pull request closed without merging**
