### PR TITLE
feat: show/hide side panels

### PR DESCRIPTION
**Pull request by Mastersam07**
Hide/Show side panels

### List of issues which are fixed by the PR
#748

### Screenrecord

https://github.com/widgetbook/widgetbook/assets/31275429/764e85ca-4f9f-4e99-8989-79b14c433ac9

### Checklist

- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on [Discord].

[CLA]: https://docs.google.com/forms/d/e/1FAIpQLScuRfjUzENsLsmQgqZlGLxMKbFi7zuXoPARyXytoyQrq7ntUw/viewform
[Discord]: https://discord.com/invite/zT4AMStAJA

### CODE REVIEW

**Comment by Mastersam07** [comment]
@YoussefRaafatNasry please review.

**Review by YoussefRaafatNasry — COMMENTED** [review]
Great work @Mastersam07!
I am pretty happy with the implementation, especially the keyboard shortcuts.
But I am kinda hesitant about the UI and how the side panels have a cutout at the top.

One layout option I have in mind is:
Having a top bar with the Widgetbook Logo and a Settings Icon that uses a dropdown to toggle side bars, and maybe has a theme toggle in the future as well.

image

I would love to explore other layouts a well. I will keep you posted if other ideas popped out.

**Comment by Mastersam07** [comment]
> Great work @Mastersam07! I am pretty happy with the implementation, especially the keyboard shortcuts. But I am kinda hesitant about the UI and how the side panels have a cutout at the top.
> 
> One layout option I have in mind is: Having a top bar with the Widgetbook Logo and a Settings Icon that uses a dropdown to toggle side bars, and maybe has a theme toggle in the future as well.
> 
> image
> 
> I would love to explore other layouts a well. I will keep you posted if other ideas popped out.

Thanks for your feedback and thoughts.

If it is fine, i could go ahead with matching the view in the image you attached. I could also wait till there are other ideas or a final expected look and update this PR to match. Let me know which works.

**Comment by atharvamalji** [comment]
Is this issue still open?

**Comment by atharvamalji** [comment]
Is this issue still open?

**Comment by YoussefRaafatNasry** [comment]
@Mastersam07 I am researching possible solutions with the team and I will get back to you in the upcoming few days once we have a more solid approach.

**Comment by YoussefRaafatNasry** [comment]
First of all, I've went on Discord to see why the user wanted to hide the side panels, as there was not enough info on the issue, and it seems to be because they want to run [Widgetbook on mobile](https://discord.com/channels/879618555560218625/1114116537188626432/1118304366307311687). So I will sadly close this PR and #748 in favor of #805. Sorry for the lack of information/planning that caused this in the first place.

Secondly, after discussions with the team on how to support Widgetbook on mobile, we came up with the following wireframe:
1. The design on big screens will be the same without any change.
1. The design on smaller screens will have a bottom bar with three icons: navigation, addons, knobs.
1. When any icon is pressed from the bottom bar, a bottom modal sheet opens.
1. The bottom modal sheets should be expandable (you can pull to top to expand, or pull to bottom to close them).

I will post this information again on #805 so it's linked with the issue.
I would highly appreciate if you could work on the new issue 💙 You can comment there so I can assign it to you if you are interested.


image

**Pull request closed without merging**
