### PR TITLE
fix: force widget tree rebuild if stateful widget is detected

### PR DESCRIPTION
**Pull request by daohoangson**
This PR tries to detect if a use case has knobs configured within a stateful widget.
- If it is the case, generate a `ValueKey` from the full URI to force everything to be rebuilt
- Otherwise, the builder is triggered without any key for better performance.

### List of issues which are fixed by the PR

https://github.com/widgetbook/widgetbook/issues/788

### Checklist

- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on [Discord].

[CLA]: https://docs.google.com/forms/d/e/1FAIpQLScuRfjUzENsLsmQgqZlGLxMKbFi7zuXoPARyXytoyQrq7ntUw/viewform
[Discord]: https://discord.com/invite/zT4AMStAJA

### CODE REVIEW

**Review by YoussefRaafatNasry — COMMENTED** [review]
Hello @daohoangson 👋 
Sorry for this taking so long :D I have been busy with a relocation process.
I've also tried to review this multiple times but I always find it hard to grasp the "check-ins" solution you proposed.
Can you explain more on how do "check-ins" differentiate between Stateless Widgets and Stateful one? Are there any other simpler solutions to solve the same problem?

**Comment by daohoangson** [comment]
Certainly.

The hypothesis is that:

1. For every use case, it is expected that each knob must be registered at least once per build.
2. Each invocation of the `register` method is treated as a check-in.
3. When a knob is updated, Flutter triggers a rebuild, and the count of check-ins is compared to the number of knobs.
4. If there are insufficient check-ins (e.g., there are 3 knobs but only 2 check-ins), it indicates that some deep deep widget property somewhere has become stale. In such cases, a `Key` is enforced to initiate a full rebuild.

For example:

- This holds true for stateless widgets because app developers typically register the knob and pass it to the constructor to configure the properties.
- In the case of providers, knobs are only registered during the `initState` (or similar mechanism). Therefore, when a knob is updated, the count of check-ins will be zero, necessitating a full rebuild with the use of a `Key`.

**Comment by YoussefRaafatNasry** [comment]
Hello @daohoangson 👋 
Thanks so much for putting the time into this, we are really grateful for it and looking for future contributions from you.
I am personally amazed by how smart the solution is, but unfortunately we will not merge this as mentioned in [this comment](https://github.com/widgetbook/widgetbook/issues/788#issuecomment-1801828212).

To show our gratitude for your efforts, we will mark this PR as a `hacktoberfest-accepted` and include it in our list of accepted PRs, to be able to claim a swag later.

**Comment by daohoangson** [comment]
Thank you for the thorough explanation, that totally makes sense. And I appreciate the PR tag, that's very thoughtful of you.

**Pull request closed without merging**
