### PR TITLE
feat: add inspector addon

### PR DESCRIPTION
**Pull request by Mastersam07**
Inspect Addon

### List of issues which are fixed by the PR
#984 

### Screenrecord

https://github.com/widgetbook/widgetbook/assets/31275429/8157528d-f9a6-4cd7-97ee-260a0e53a936

### Checklist

- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on [Discord].

[CLA]: https://docs.google.com/forms/d/e/1FAIpQLScuRfjUzENsLsmQgqZlGLxMKbFi7zuXoPARyXytoyQrq7ntUw/viewform
[Discord]: https://discord.com/invite/zT4AMStAJA

### CODE REVIEW

**Review by YoussefRaafatNasry — CHANGES_REQUESTED** [review]
Well done! This will be a really helpful addon for all users.

We just need to name all occurances of "inspect" addon to "inspector" addon, this includes files, docs, code, etc.

**Comment by Mastersam07** [comment]
Changes made as requested. @YoussefRaafatNasry

**Comment by YoussefRaafatNasry** [comment]
@Mastersam07 There are still a lot of files/folders names `inspect_addon` instead of `inspector_addon`:

- `docs/addons/inspect-addon.mdx`
- `packages/widgetbook/lib/src/addons/inspect_addon/inspect_addon.dart` (file and folder)
- `packages/widgetbook/test/src/addons/inspect_addon_test.dart`

**Review by YoussefRaafatNasry — CHANGES_REQUESTED** [review]
@Mastersam07 There are still a lot of files/folders named `inspect_addon` instead of `inspector_addon`:

- `docs/addons/inspect-addon.mdx`
- `packages/widgetbook/lib/src/addons/inspect_addon/inspect_addon.dart` (file and folder)
- `packages/widgetbook/test/src/addons/inspect_addon_test.dart`

**Comment by Mastersam07** [comment]
> @Mastersam07 There are still a lot of files/folders named `inspect_addon` instead of `inspector_addon`:
> 
> * `docs/addons/inspect-addon.mdx`
> * `packages/widgetbook/lib/src/addons/inspect_addon/inspect_addon.dart` (file and folder)
> * `packages/widgetbook/test/src/addons/inspect_addon_test.dart`

Alright. Done.

**Review by YoussefRaafatNasry — APPROVED** [review]

**Pull request merged**
